# CI workflow to build and test a Nest.js app.
# Sets up Node, performs a clean install, runs lint, compiles typescript, e2e tests, coverage.
# Builds production build title next.js-build and uploads as artifact.
# Workflow runs on ubuntu-latest and uses matrix build for Node version.

name: Continuous Integration
run-name: Node.js CI
on:
  workflow_call: # required when creating a reusable workflow
#    inputs:
#      config-path:
#        required: false
#        type: string
#    secrets:
#      token:
#        required: false
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'
      - name: Clean install
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Compile typescript
        run: npm run compile
      #        env:
      #          MONGODB_URI: ${{ secrets.MONGODB_URI }}
      # - name: Jest e2e tests
      #   run: npm run test:e2e
      - name: Test coverage
        run: npm run test:cov

      #      - name: Run Snapshot Tests
      #        run: npm run test:snapshot
      #
      #      - name: Run Routing Tests
      #        run: npm run test:routing
      #
      #      - name: Run API Tests
      #        run: npm run test:api
      #
      #      - name: Run Integration Tests
      #        run: npm run test:integration

      - name: Build App
        run: npm run build --if-present

      # https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts
      - name: Archive Next.js build
        uses: actions/upload-artifact@v4
        with:
          name: nest.js-build
          path: dist/
          retention-days: 14

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: docs/coverage/index.html
          retention-days: 14
