# This is a simple test to check if the SSH key is working and if the user has sudo access
# The SSH key is stored in the secrets of the repository and is used to connect to the remote server

name: SSH Access Test Version 2.3
run-name: SSH and Sudo Test
on: [workflow_dispatch]

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    environment: test_env

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH Key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_KEY  }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Test SSH Connection and Execute whoami
        run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa deployuser@35.86.119.51 whoami
