name: Deploy test 3.91
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test_env

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install SSH Key
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Execute Deployment Commands
      run: |
        ssh -o StrictHostKeyChecking=no deployuser@35.86.119.51 << 'EOF'
          # Ensure you're in the correct directory
          cd /path/to/your/nestjs/project

          # Fetch the latest changes
          git pull origin main

          # Install any new dependencies
          npm install

          # Build the project
          npm run build

          # Restart the application with PM2
          pm2 restart nscEventsNestServer
        EOF
