# This is a simple test to check if the SSH key is working and if the user has sudo access
# The SSH key is stored in the secrets of the repository and is used to connect to the remote server

name: Deployment Test 2.8
run-name: SSH and Sudo Test
on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH for Deployment
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Execute Deployment Commands
      run: |
        ssh -o StrictHostKeyChecking=no deployuser@35.86.119.51 << 'EOF'
          # Cd into server dir
          cd nestServer/

          # Pull the latest changes from the main branch
          git pull origin main

          # Install dependencies
          npm install

          # Build the project
          npm run build

          # Restart the application using PM2
          pm2 restart nscEventsNestServer
        EOF
